name: Deploy

on:
  workflow_dispatch:  # Add this line to enable manual triggering
  # other triggers, e.g., push, pull_request, etc.
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy
      run: echo "Deploying..."
      # Add your deploy steps here
